// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Ifelsik/url-shortener/internal/app/url"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAddURL creates a new instance of MockAddURL. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAddURL(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAddURL {
	mock := &MockAddURL{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAddURL is an autogenerated mock type for the AddURL type
type MockAddURL struct {
	mock.Mock
}

type MockAddURL_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAddURL) EXPECT() *MockAddURL_Expecter {
	return &MockAddURL_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockAddURL
func (_mock *MockAddURL) Handle(ctx context.Context, request *url.AddURLRequest) (*url.AddURLResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 *url.AddURLResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *url.AddURLRequest) (*url.AddURLResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *url.AddURLRequest) *url.AddURLResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*url.AddURLResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *url.AddURLRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAddURL_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockAddURL_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - request *url.AddURLRequest
func (_e *MockAddURL_Expecter) Handle(ctx interface{}, request interface{}) *MockAddURL_Handle_Call {
	return &MockAddURL_Handle_Call{Call: _e.mock.On("Handle", ctx, request)}
}

func (_c *MockAddURL_Handle_Call) Run(run func(ctx context.Context, request *url.AddURLRequest)) *MockAddURL_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *url.AddURLRequest
		if args[1] != nil {
			arg1 = args[1].(*url.AddURLRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAddURL_Handle_Call) Return(addURLResponse *url.AddURLResponse, err error) *MockAddURL_Handle_Call {
	_c.Call.Return(addURLResponse, err)
	return _c
}

func (_c *MockAddURL_Handle_Call) RunAndReturn(run func(ctx context.Context, request *url.AddURLRequest) (*url.AddURLResponse, error)) *MockAddURL_Handle_Call {
	_c.Call.Return(run)
	return _c
}
