// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Ifelsik/url-shortener/internal/app/user"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAddUser creates a new instance of MockAddUser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAddUser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAddUser {
	mock := &MockAddUser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAddUser is an autogenerated mock type for the AddUser type
type MockAddUser struct {
	mock.Mock
}

type MockAddUser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAddUser) EXPECT() *MockAddUser_Expecter {
	return &MockAddUser_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockAddUser
func (_mock *MockAddUser) Handle(ctx context.Context, request *user.AddUserRequest) (*user.AddUserResponse, error) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 *user.AddUserResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.AddUserRequest) (*user.AddUserResponse, error)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *user.AddUserRequest) *user.AddUserResponse); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.AddUserResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *user.AddUserRequest) error); ok {
		r1 = returnFunc(ctx, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAddUser_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockAddUser_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - request *user.AddUserRequest
func (_e *MockAddUser_Expecter) Handle(ctx interface{}, request interface{}) *MockAddUser_Handle_Call {
	return &MockAddUser_Handle_Call{Call: _e.mock.On("Handle", ctx, request)}
}

func (_c *MockAddUser_Handle_Call) Run(run func(ctx context.Context, request *user.AddUserRequest)) *MockAddUser_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *user.AddUserRequest
		if args[1] != nil {
			arg1 = args[1].(*user.AddUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAddUser_Handle_Call) Return(addUserResponse *user.AddUserResponse, err error) *MockAddUser_Handle_Call {
	_c.Call.Return(addUserResponse, err)
	return _c
}

func (_c *MockAddUser_Handle_Call) RunAndReturn(run func(ctx context.Context, request *user.AddUserRequest) (*user.AddUserResponse, error)) *MockAddUser_Handle_Call {
	_c.Call.Return(run)
	return _c
}
