// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIdentifier creates a new instance of MockIdentifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIdentifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIdentifier {
	mock := &MockIdentifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIdentifier is an autogenerated mock type for the Identifier type
type MockIdentifier struct {
	mock.Mock
}

type MockIdentifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIdentifier) EXPECT() *MockIdentifier_Expecter {
	return &MockIdentifier_Expecter{mock: &_m.Mock}
}

// String provides a mock function for the type MockIdentifier
func (_mock *MockIdentifier) String() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIdentifier_String_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'String'
type MockIdentifier_String_Call struct {
	*mock.Call
}

// String is a helper method to define mock.On call
func (_e *MockIdentifier_Expecter) String() *MockIdentifier_String_Call {
	return &MockIdentifier_String_Call{Call: _e.mock.On("String")}
}

func (_c *MockIdentifier_String_Call) Run(run func()) *MockIdentifier_String_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIdentifier_String_Call) Return(s string) *MockIdentifier_String_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIdentifier_String_Call) RunAndReturn(run func() string) *MockIdentifier_String_Call {
	_c.Call.Return(run)
	return _c
}
